spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://i8a301.p.ssafy.io:3306/sccs?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 54.180.164.128

  mail:
    host: smtp.gmail.com
    port: 587
    username: dojsfffff@gmail.com
    password: hpelcyekkeldcuvi
    properties:
      debug: true
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.scss.api.*.*

jwt:
  secret: oekcERFVSD3nvc9vdSGci3dzke3f09cDFiv9we3uihcdskj3vcnhzvredxzvuheanwaDDSFf3fuhvcxzGVFsgjvhnbdas8ghrf4whfgdsafvcijhsdiufgh

logging:
  level:
    root: debug

file:
    dir: /home/project/judgeonline/sccs-online-judge/src/main/resources/algo/

server:
  port: 8200