spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/sccs?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sccs?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.scss.api.*.*

logging:
  level:
    root: debug

file:
    dir: C:/S08P12A301/backend/src/main/resources/file/